SET NAMES UTF8;
DROP DATABASE IF EXISTS tour;
CREATE DATABASE tour CHARSET=UTF8;
USE tour;


CREATE TABLE tour_user(
  uid INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(11) NOT NULL,
  password VARCHAR(32) NOT NULL,
  nickname VARCHAR(32) DEFAULT NULL
);
INSERT INTO tour_user VALUES(NULL,'dingding','qq1234567','撅腚的兔子');
